### ISSUE TITLE
Mediawiki 1.26.2 - Installed but not working

### ISSUE THREAD

**Issue by jorel83** [mediawiki4intranet/IntraACL#45]
Hi,

Running a Mediawiki 1.26.2 on a RBPI2, with IntraACl 2.1.8, and it's surley installed and I applied the patch for 1.26 and ran update.php, when trying to apply a ACL or create a Group, the only thing that happens, is that it deletes everything on the Mainpage (regardless from where i try to apply the ACL that happens). One more thing that i noticed, its not possible to search for users to add to the ACL/Group i want to create, which normally is a Autocomplete function in an other wiki im running.

Appreciate any assistance, and thanks for this (normally) wery good working ACL!

**Comment by vitalif** [comment]
Can you try the master branch? 2.1.8's ACL editor is only compatible with mediawiki up to 1.25 because legacy js functions were dropped in 1.26.

**Comment by jorel83** [comment]
I took the link from from the master branch and cloned it to extensions dir in mediawiki, it shows up as 2.1.8 in the Specialpages:version. I just tried to get the Zip-file from master and extracted it into the extensions, ran the patch and update but same issue as earlier. Cant find any normal errors neither, any suggestions?

**Comment by vitalif** [comment]
That's very strange. I have several 1.26.0 installations and IntraACL works fine on them.
If you're saying it's always overwriting the main page instead of saving ACL text from the editor it seems IntraACL is submitting its form with incorrect parameters...
Can you log the POST request which happens on saving ACL using the developer console of your browser and post the details here?

Also you can try to create an ACL definition by hand by copying its text from another wiki. I.e. create article named "ACL:Page/<Page_name>" with content like for example "{{#manage rights: assigned to = User:<Your_Username>}}". If the page will get the protection after doing this IntraACL is working fine except the ACL editor :)

**Comment by jorel83** [comment]
Thanks for the details, there is qiute a bit of information so gathered the results here: https://drive.google.com/file/d/0Bx0nTGpZkfFOd0JYeHZ6dzVPd2M/view?usp=sharing

Wasn't 100% sure if the page name should be exactly ACL:Page/ but tried that, and put my username as "{{#manage rights: assigned to = User:Mysusername}}", got "Exception encountered, of type "Exception" Mgmt console details is in the log.

Let me know if something is missing done wrongly or if i can do something else to get it working. It runs fine on my other wiki in a production environment but on Mediawiki 1.25.X.

**Comment by vitalif** [comment]
I've meant "ACL:Page/\<Page_name>", that's markdown that has eaten \<Page_name> :)
The first lines of your log are saying that you're missing collapsibleTabs dependency for some other js resource module (not IntraACL because it's not using that dependency). This probably prevents IntraACL javascripts from running. Did you install 1.25 version of vector skin on mediawiki 1.26?..

**Comment by jorel83** [comment]
I see :) 

I'm running the default Vector skin, but just to make sure cloned the current REL1.26 from git and running the skin from a new catalog. I also tried to create a ACL-page for an artile, that seems to work tried accessing that page with another user and it stops me.

I guess that some js or such isn't working properly?

**Comment by vitalif** [comment]
Yes. Do you have any other extensions installed?

**Comment by jorel83** [comment]
These are activated in the Localsettings.php

require_once( "$IP/extensions/CategoryTree/CategoryTree.php" );
require_once( "$IP/extensions/Cite/Cite.php" );
require_once( "$IP/extensions/ConfirmEdit/ConfirmEdit.php" );
require_once( "$IP/extensions/CreateBox/CreateBox.php" );
require_once( "$IP/extensions/Gadgets/Gadgets.php" );
require_once( "$IP/extensions/ImageMap/ImageMap.php" );
require_once( "$IP/extensions/InputBox/InputBox.php" );
require_once( "$IP/extensions/LanguageSelector/LanguageSelector.php" );
require_once( "$IP/extensions/NewestPages/NewestPages.php" );
require_once( "$IP/extensions/News/News.php" );
require_once( "$IP/extensions/ParserFunctions/ParserFunctions.php" );
require_once( "$IP/extensions/Renameuser/Renameuser.php" );
require_once( "$IP/extensions/Vector/Vector.php" );
require_once( "$IP/extensions/VisualEditor/VisualEditor.php");
# Privatewiki, need networkauth to use VisualEditor.
require_once( "$IP/extensions/NetworkAuth/NetworkAuth.php" );
include_once ("$IP/extensions/IntraACL/includes/HACL_Initialize.php");

**Comment by jorel83** [comment]
Found the issue, looks like disabling: require_once( "$IP/extensions/VisualEditor/VisualEditor.php"); was the trick! :-)

**Comment by vitalif** [comment]
Ok great that you've solved your problem :)
VE is a delicate extension, its master branch usually doesn't work in older MW's...
