### ISSUE TITLE
View Rights on Graph Exception

### ISSUE THREAD

**Issue by Serze** [mediawiki4intranet/IntraACL#58]
Exception encountered, of type "Exception"
[51144935] /domain.com/index.php?title=Special:IntraACL&action=rightgraph Exception from line 382 of /var/www/html/domain.com/extensions/IntraACL/includes/Definition.php: BUG: Definition (4, 61) is saved, but PE does not exist!
Backtrace:
#0 /var/www/html/domain.com/extensions/IntraACL/includes/Definition.php(158): IACLDefinition->get_pe_title()
#1 /var/www/html/domain.com/extensions/IntraACL/includes/ACLSpecial.php(173): IACLDefinition->offsetGet(string)
#2 /var/www/html/domain.com/extensions/IntraACL/includes/ACLSpecial.php(115): IntraACLSpecial->html_rightgraph(array)
#3 /var/www/html/domain.com/includes/specialpage/SpecialPage.php(384): IntraACLSpecial->execute(NULL)
#4 /var/www/html/domain.com/includes/specialpage/SpecialPageFactory.php(553): SpecialPage->run(NULL)
#5 /var/www/html/domain.com/includes/MediaWiki.php(281): SpecialPageFactory::executePath(Title, RequestContext)
#6 /var/www/html/domain.com/includes/MediaWiki.php(714): MediaWiki->performRequest()
#7 /var/www/html/domain.com/includes/MediaWiki.php(508): MediaWiki->main()
#8 /var/www/html/domain.com/index.php(41): MediaWiki->run()
#9 {main}

This happens when I click view rights on graph.

**Comment by vitalif** [comment]
This means there's an inconsistency in your database - it has IntraACL rules for pages/categories that do not exist anymore. This was caused by IntraACL not deleting rules for deleted pages - I've just fixed it in a commit (please update).
To correct your DB you should additionally run SQL `delete from i using intraacl_rules i left join page p on page_id=pe_id where pe_type in (2,4,10) and page_id is null;`

**Comment by Serze** [comment]
What does this mean? 

Fatal error: Call to a member function getPrefixedText() on a non-object in /var/www/html/wiki.ranchehrlo.ca/extensions/IntraACL/includes/ACLSpecial.php on line 383

When I click view rights graph.
